export const TICKER_LIST: { symbol: string; name: string }[] = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'ASML', name: 'ASML Holding N.V.' },
  { symbol: 'KLAC', name: 'KLA Corporation' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'IBM', name: 'International Business Machines' },
  { symbol: 'NOW', name: 'ServiceNow Inc.' },
  { symbol: 'WDAY', name: 'Workday Inc.' },
  { symbol: 'SNOW', name: 'Snowflake Inc.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'NET', name: 'Cloudflare Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.' },
  { symbol: 'COIN', name: 'Coinbase Global Inc.' },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc.' },
  { symbol: 'SHOP', name: 'Shopify Inc.' },
  { symbol: 'SQ', name: 'Block Inc.' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.' },
  { symbol: 'LYFT', name: 'Lyft Inc.' },
  { symbol: 'ABNB', name: 'Airbnb Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'RBLX', name: 'Roblox Corporation' },
  { symbol: 'SNAP', name: 'Snap Inc.' },
  { symbol: 'PINS', name: 'Pinterest Inc.' },
  { symbol: 'SPOT', name: 'Spotify Technology S.A.' },
  { symbol: 'TTD', name: 'The Trade Desk Inc.' },
  { symbol: 'TWLO', name: 'Twilio Inc.' },
  { symbol: 'HUBS', name: 'HubSpot Inc.' },
  { symbol: 'TEAM', name: 'Atlassian Corporation' },
  { symbol: 'MDB', name: 'MongoDB Inc.' },
  { symbol: 'ZM', name: 'Zoom Video Communications Inc.' },
  { symbol: 'DOCU', name: 'DocuSign Inc.' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc.' },
  { symbol: 'AFRM', name: 'Affirm Holdings Inc.' },
  { symbol: 'UPST', name: 'Upstart Holdings Inc.' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc.' },
  { symbol: 'LCID', name: 'Lucid Group Inc.' },
  { symbol: 'NIO', name: 'NIO Inc.' },
  { symbol: 'XPEV', name: 'XPeng Inc.' },
  { symbol: 'LI', name: 'Li Auto Inc.' },
  { symbol: 'BABA', name: 'Alibaba Group Holding Ltd.' },
  { symbol: 'JD', name: 'JD.com Inc.' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.' },
  { symbol: 'SE', name: 'Sea Limited' },
  { symbol: 'MELI', name: 'MercadoLibre Inc.' },
  { symbol: 'GME', name: 'GameStop Corp.' },
  { symbol: 'AMC', name: 'AMC Entertainment Holdings Inc.' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'BAC', name: 'Bank of America Corporation' },
  { symbol: 'GS', name: 'The Goldman Sachs Group Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'AXP', name: 'American Express Company' },
  { symbol: 'BLK', name: 'BlackRock Inc.' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corporation' },
  { symbol: 'COF', name: 'Capital One Financial Corporation' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'MA', name: 'Mastercard Inc.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.' },
  { symbol: 'MRNA', name: 'Moderna Inc.' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'CVS', name: 'CVS Health Corporation' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'SLB', name: 'SLB (Schlumberger)' },
  { symbol: 'EOG', name: 'EOG Resources Inc.' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corporation' },
  { symbol: 'DVN', name: 'Devon Energy Corporation' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'TGT', name: 'Target Corporation' },
  { symbol: 'HD', name: 'The Home Depot Inc.' },
  { symbol: 'LOW', name: "Lowe's Companies Inc." },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'NKE', name: 'NIKE Inc.' },
  { symbol: 'DIS', name: 'The Walt Disney Company' },
  { symbol: 'PG', name: 'Procter & Gamble Co.' },
  { symbol: 'KO', name: 'The Coca-Cola Company' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'PM', name: 'Philip Morris International Inc.' },
  { symbol: 'MO', name: 'Altria Group Inc.' },
  { symbol: 'BA', name: 'The Boeing Company' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'GE', name: 'GE Aerospace' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'UPS', name: 'United Parcel Service Inc.' },
  { symbol: 'FDX', name: 'FedEx Corporation' },
  { symbol: 'RTX', name: 'RTX Corporation' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation' },
  { symbol: 'GD', name: 'General Dynamics Corporation' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'AMT', name: 'American Tower Corporation' },
  { symbol: 'PLD', name: 'Prologis Inc.' },
  { symbol: 'EQIX', name: 'Equinix Inc.' },
  { symbol: 'O', name: 'Realty Income Corporation' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.' },
  { symbol: 'DUK', name: 'Duke Energy Corporation' },
  { symbol: 'SO', name: 'The Southern Company' },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF' },
  { symbol: 'GLD', name: 'SPDR Gold Shares' },
  { symbol: 'SLV', name: 'iShares Silver Trust' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF' },
  { symbol: 'HYG', name: 'iShares High Yield Corporate Bond ETF' },
  { symbol: 'XLF', name: 'Financial Select Sector SPDR Fund' },
  { symbol: 'XLE', name: 'Energy Select Sector SPDR Fund' },
  { symbol: 'XLK', name: 'Technology Select Sector SPDR Fund' },
  { symbol: 'XLV', name: 'Health Care Select Sector SPDR Fund' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { symbol: 'BND', name: 'Vanguard Total Bond Market ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF' },
  { symbol: 'IAU', name: 'iShares Gold Trust' },
  { symbol: 'SCHD', name: 'Schwab US Dividend Equity ETF' },
  { symbol: 'VIG', name: 'Vanguard Dividend Appreciation ETF' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B' },
  { symbol: 'BRK.A', name: 'Berkshire Hathaway Inc. Class A' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.' },
  { symbol: 'PARA', name: 'Paramount Global' },
  { symbol: 'SONY', name: 'Sony Group Corporation' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor Manufacturing' },
  { symbol: 'SAMSUNG', name: 'Samsung Electronics Co. Ltd.' },
  { symbol: 'RACE', name: 'Ferrari N.V.' },
  { symbol: 'LVMH', name: 'LVMH Mo\u00ebt Hennessy Louis Vuitton' },
  { symbol: 'TM', name: 'Toyota Motor Corporation' },
  { symbol: 'HMC', name: 'Honda Motor Co. Ltd.' },
  { symbol: 'F', name: 'Ford Motor Company' },
  { symbol: 'GM', name: 'General Motors Company' },
  { symbol: 'STLA', name: 'Stellantis N.V.' },
  { symbol: 'WOLF', name: 'Wolfspeed Inc.' },
  { symbol: 'ARM', name: 'Arm Holdings plc' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.' },
  { symbol: 'DELL', name: 'Dell Technologies Inc.' },
  { symbol: 'HPQ', name: 'HP Inc.' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise Co.' },
  { symbol: 'ACN', name: 'Accenture plc' },
  { symbol: 'SAP', name: 'SAP SE' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'MSCI', name: 'MSCI Inc.' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'MCO', name: "Moody's Corporation" },
  { symbol: 'ICE', name: 'Intercontinental Exchange Inc.' },
  { symbol: 'CME', name: 'CME Group Inc.' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc.' },
  { symbol: 'USB', name: 'U.S. Bancorp' },
  { symbol: 'PNC', name: 'PNC Financial Services Group Inc.' },
  { symbol: 'TFC', name: 'Truist Financial Corporation' },
]
